apiVersion: v1
kind: ConfigMap
metadata: 
  name: web-collector-conf
  labels:
    app: opentelemetry-collector
    component: web-collector-conf
data:
  web-collector-config: |
    receivers:
      otlp:
        endpoint: "0.0.0.0:55680"
    processors:
      batch:
      memory_limiter:
        ballast_size_mib: 700
        limit_mib: 1500
        spike_limit_mib: 100
        check_interval: 5s
      queued_retry:
    extensions:
      health_check: {}
    exporters:
      otlp:
        endpoint: "ingest.lightstep.com:443"
        headers:
          "lightstep-access-token": <insert access token>
    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch, queued_retry]
          exporters: [otlp]
